### ISSUE TITLE
News alert bar

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1055]
@GeorgeBellTMH @itbel 

You guys know that yellow bar we use for Live events? That was originally intended for weather alerts (with an animation that runs the text through the yellow bar). 

Here is what I'm thinking...what would it take for it to be possible to use that bar for both live and news? I know we'd need to account for Sunday mornings when we're live AND possibly have a news item. But barring that, what would it take from you guys' seat?

**Comment by GeorgeBellTMH** [comment]
Not much. But maybe it might be better to use the yellow hero thing we have (which we have been using for community updates)…since it’s already customizable…just make it say Weather Alerts…and link it to a page with details…Sent from my iPhoneOn Sep 25, 2022, at 9:12 AM, Lucas Belem ***@***.***> wrote:﻿
@GeorgeBellTMH @itbel
You guys know that yellow bar we use for Live events? That was originally intended for weather alerts (with an animation that runs the text through the yellow bar).
Here is what I'm thinking...what would it take for it to be possible to use that bar for both live and news? I know we'd need to account for Sunday mornings when we're live AND possibly have a news item. But barring that, what would it take from you guys' seat?
