### ISSUE TITLE
Our Team Module - Local Church Pages and staff pages.

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#126]
The first module under the hero on every Meeting House local church page is "Our Team". Currently we have an MVP version running, but want to update this section to look the same as in the final UI design for desktop, mobile, and tablet. 
See the local sites design here: https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI-GitHub-Sharing?node-id=571%3A655
See the staff page design here: https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI-GitHub-Sharing?node-id=1859%3A17607
Any specific questions ask David or Lucas!

**Comment by JonEsparaz** [comment]
@lucastbelem @deeinstereo are we going to collect Instagram/Twitter handles from staff?

**Comment by lucastbelem** [comment]
@JonEsparaz For the purposes of what you're developing, can we make it so it's possible, but don't display if not available? I'm saying this because a) collecting them all may take a bit of time; b) we may want to only display those for pastors; c) it may be only twitter; d) not all of our pastors/staff will have twitter handles.

**Comment by JonEsparaz** [comment]
Yup definitely. It’ll only show up if the required data is available.
