### ISSUE TITLE
Spiritually Curious Video Layout - Spiritually Curious Page

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#130]
Here's the link to figma UI: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=1828%3A15243

Directly under the Starting Questions header we should be able to see the six videos we have available (on the Figma UI design they are represented by white boxes).
Currently it's just a playlist the user can scroll through. There should also be a show more button that loads six additional videos.

**Comment by JonEsparaz** [comment]
I'll chip away at this over the next couple weeks.

**Comment by JonEsparaz** [comment]
I'm going to take a crack at this instead of #127 since COVID-19 means there aren't events to display.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH while working on the UI for this, I noticed that there's an issue with the query for the videos. The Spiritually Curious videos are displayed in the follow order by episode number: 6,3,4,1,5,2 (I assume it should be ascending).

I was digging around `src/graphql-custom/customQueries.ts` and `src/components/RenderRouter/DataLoader.ts`, but couldn't identify the issue. Any ideas?

**Comment by georgevicbell** [comment]
It’s likely because it is sorted by the episode date instead of by episode number...

Options:

1.the easiest way to fix it is likely to just not show the episode number for questions
2. renumber the episodes
3. change their dates to lineup with the existing episode numbers


Sent from my iPhone

On Mar 19, 2020, at 6:17 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@GeorgeBellTMH<https://github.com/GeorgeBellTMH> while working on the UI for this, I noticed that there's an issue with the query for the videos. The Spiritually Curious videos are displayed in the follow order by episode number: 6,3,4,1,5,2 (I assume it should be ascending).

I was digging around src/graphql-custom/customQueries.ts and src/components/RenderRouter/DataLoader.ts, but couldn't identify the issue. Any ideas?
