### ISSUE TITLE
Watch page update

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#161]
We need to update the experience provided on our watch page (when someone is watching a video). Go to themeetinghouse.com/teaching and click "watch" on the teaching to see the current experience. Here is what it should look like: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=289%3A25

- Duration should be displayed
- Ability to share to social media
- Design of "Notes", "Download Audio" and "Download Video" needs updating
- Podcasts should be added to the bottom of the page
- Highlights reel needs to be made available
- Positioning, spacing, and styling need updating

**Comment by JonEsparaz** [comment]
I'll try and get to this today.

**Comment by JonEsparaz** [comment]
@lucastbelem a couple questions:
- What social media platforms should the share button have?
- What content is supposed to be in highlight reels? Is it just other videos from the series?

**Comment by lucastbelem** [comment]
@JonEsparaz Cool!

- Twitter, Instagram, Facebook. @deeinstereo anything else?
- The highlights reel is supposed to be our teaser videos. You know the 2-3 minutes we would post throughout the week after the teaching was live in Oakville so that other sites could see what was coming up? That's it. Currently, the videos aren't labelled as "highlights" in the admin side...but we'll need to get that switched at some point. Anyways, just giving you that for context.

**Comment by lucastbelem** [comment]
Maybe email too?

**Comment by JonEsparaz** [comment]
Sounds good. Not too sure if Instagram is possible since we're sharing links, but I'll look into it.

**Comment by JonEsparaz** [comment]
@deeinstereo the share button package I'm using allows us to add optional content. Let me know if you want any of the following:

**Email**
- subject
- body

**Facebook**
- quote
- hashtag

**Twitter**
- title (this changes the title of the shared page on the card)
- via (like via YouTube when you share from YouTube)
- hashtags
- related (we can suggest accounts to follow: e.g. Bruxy, TMH, Jesus Collective)

More detail can be found here: https://github.com/nygardk/react-share#readme

**Comment by JonEsparaz** [comment]
@lucastbelem should the podcast links point to the specific episode? What is the functionality of the "subscribe" button - does it also point to Apple Podcasts?

**Comment by deeinstereo** [comment]
@JonEsparaz yeah no go on Instagram, good catch. 

Email
- Subject: Can this change based on the title of the video? If not, then how about Check out this video from The Meeting House
-Body: I wanted to share this video with you. 
_Thoughts? I'm not 100% sure what's best here so I lean on what you think might work_

Facebook
- Can the quote be related to the title of the video? 
-no hashtag, @The Meeting House FB account if possible

Twitter
- yes
- yes
- nah
- just @themeetinghouse twitter account 


The subscribe button would ideally let them subscribe to the RSS feed, but since most people use a podcatcher I don't see the value of that. Maybe we should remove that, or just point them to Apple Podcasts (although the link already does this right?)

**Comment by JonEsparaz** [comment]
@deeinstereo here's what I implemented:

Email
- Subject: Check out <video title as on YouTube> from The Meeting House (I pulled from YouTube so that the series title and episode number is included)
-Body: I wanted to share this video with you: <link>

Facebook
- Quote: <video title as on YouTube> from The Meeting House (same reason for pulling from YouTube)
-@ FB account isn't possible unfortunately. 

Twitter
As you above.

If for whatever reason the YouTube title doesn't exist in the DB I default to "Check out this video from The Meeting House"

**Comment by JonEsparaz** [comment]
> The subscribe button would ideally let them subscribe to the RSS feed, but since most people use a podcatcher I don't see the value of that. Maybe we should remove that, or just point them to Apple Podcasts (although the link already does this right?)

During the Tuesday meeting, Georege suggested a menu that expands with links to other popular podcatchers, so I think we'll go with that.

**Comment by JonEsparaz** [comment]
Some initial work on the podcasts module:

![image](https://user-images.githubusercontent.com/48423418/81456128-4abc5a80-915f-11ea-9b52-966f738d363e.png)

Should be finished on Monday. @deeinstereo let me know if the descriptions are good (one I took from Figma and the other I took from a snippet from [https://www.themeetinghouse.com/teaching-podcasts](https://www.themeetinghouse.com/teaching-podcasts)).

**Comment by deeinstereo** [comment]
@JonEsparaz looks good, just make sure the right description is matched to the right podcast. Based on that Screen shot the meeting house after party podcast descriptions seems off. We also make sure that the descriptions are updated on Spotify and Apple Podcasts so you can look there to triple check. 

If you want suggestions for popular podcatchers, after Apple our most popular are:
Spotify
PodBean
Google Podcasts 

Also, I think that the lock up of the apple + iTunes is incorrect. Look here for rules about which icon goes with which CTA: https://www.apple.com/itunes/marketing-on-podcasts/identity-guidelines.html

Thanks Jon!

**Comment by JonEsparaz** [comment]
@deeinstereo sounds good. I’ll get the description from Apple podcasts and use their lockup. I’ll make sure to read the docs from the other podcatchers too

**Comment by JonEsparaz** [comment]
I'm going to close this issue and open new issues for the remaining sub-issues since they are a little bit more involved and this issue is getting a bit messy (see #214, #215 and #216).
