### ISSUE TITLE
Instagram Pull

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#163]

**Comment by lucastbelem** [comment]
Design as per: https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI-GitHub-Sharing?node-id=681%3A8285

**Comment by nikklassen** [comment]
I can probably look into this one

**Comment by nikklassen** [comment]
It looks like this is going to require some backend/admin page work. The new Instagram API requires that users grant an app permission to read their feed. So if we want to do this, someone with access to the Instragram accounts will have to authorize our app ahead of time, and store an auth token for each site's account. We would then have to proxy a visitor's calls so that we can refresh the token if needed.

**Comment by georgevicbell** [comment]
Yah, I think we would add the calls to the amplify graph API to do that....we currently are doing that on the admin side with YouTube and F1...that code is under the amplify/backend/API/meetinghouse folder...the *.req.vtl and *.res.vtl files do most of the work (the keys are not on github for obvious reasons)...

If you point me to the docs I can setup the keys.



Sent from my iPhone

On Jun 7, 2020, at 1:46 PM, Nik Klassen <notifications@github.com> wrote:

﻿

It looks like this is going to require some backend/admin page work. The new Instagram API requires that users grant an app permission to read their feed. So if we want to do this, someone with access to the Instragram accounts will have to authorize our app ahead of time, and store an auth token for each site's account. We would then have to proxy a visitor's calls so that we can refresh the token if needed.

**Comment by nikklassen** [comment]
The walkthrough that most closely covers this use case is at https://developers.facebook.com/docs/instagram-basic-display-api/getting-started

**Comment by JonEsparaz** [comment]
If we're not able to get the API tokens set up, might I suggest we try this:

```javascript
const https = require('https');
const instagramUser = '';
const url = `https://www.instagram.com/${instagramUser}/?__a=1`;

https.get(url, (res) => {
    let body = "";

    res.on("data", (chunk) => {
        body += chunk;
    });

    res.on("end", () => {
        try {
            const json = JSON.parse(body);
            const media = json.graphql.user.edge_owner_to_timeline_media.edges;
            media.forEach(element => {
                if (element.node['__typename'] === 'GraphImage') {
                    //write data to DynamoDB and/or save to S3
                }
            });
        } catch (error) {
            console.error(error.message);
        };
    });
}).on("error", (error) => {
    console.error(error.message);
});
```

I assume we can setup a scheduled Lambda to do this for each site.

**Comment by nikklassen** [comment]
It looks like this is the internal API, which should work, but paging requires a hash you don't get from this "view". But that probably doesn't matter if we just want to preview the account.

**Comment by GeorgeBellTMH** [comment]
Yup, lets do the simple one, don't need paging...key management for insta is a bit of a pain for 20+ sites.

**Comment by JonEsparaz** [comment]
I'll set up a scheduled Lambda. I just need to figure out a good way to have it scrape each site separately (we don't want the entire job to fail if just one site fails).

**Comment by JonEsparaz** [comment]
Related: https://github.com/themeetinghouse/mobile/issues/43

**Comment by GeorgeBellTMH** [comment]
Closing...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH isn't there work left on this for the website?
