### ISSUE TITLE
Curated Playlists Baby Hero Image

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#227]
Black bars from the YouTube thumbnail don't look great. Is there an actual baby hero image for BBQs?

![image](https://user-images.githubusercontent.com/48423418/82107583-f2550200-96f6-11ea-9222-ebc82a08fb96.png)

**Comment by deeinstereo** [comment]
@JonEsparaz good catch. Ask and you shall receive! Can we just leave this one semi-permanently instead of switching with each new video? Also do you know what to do to make this work or does @lucastbelem need to upload it somewhere? 
![BBQ_BabyHero](https://user-images.githubusercontent.com/47831068/82476256-c2618200-9a9b-11ea-81a7-aaf3040397a7.jpg)

**Comment by JonEsparaz** [comment]
Thanks - looks great. Lucas has to put it in a specific folder.

**Comment by JonEsparaz** [comment]
Actually, we need a edit a tiny bit of code... PR coming (I will upload the image too).

**Comment by JonEsparaz** [comment]
@deeinstereo so the image is stored in [`/public/static/photos/series/baby-hero`](https://github.com/themeetinghouse/web/tree/master/public/static/photos/series/baby-hero) along with all the other baby hero images, and each is associated with a series (in this case BBQs) by it's file name matching the pattern `videoType-seriesTitle.jpg` (in this case `bbq-Bruxy's Bag of Questions.jpg`).

**Comment by deeinstereo** [comment]
@JonEsparaz Awesome! Can we push this? Do @lucastbelem or I need to do anything?

**Comment by JonEsparaz** [comment]
@deeinstereo George just has to merge my PR
