### ISSUE TITLE
Local teaching playlist (especially for EFCs)

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#410]

**Comment by GeorgeBellTMH** [comment]
@lucastbelem @deeinstereo we could probably include any teaching by the local pastor on the parish page as well...for some sites this may be a nice to have...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH for sure. The questions are these:

Do we want to include Parish teaching on Parish pages? The issue is we don't control quality for these because they are done locally. Some just record on iPhones. 
If we do want it, how do we get the videos? We can get pastors to share the files with us, but for EFCs, we don't normally store that on our YouTube channel. Would we want to or do we work on that multiple youtube channel solution?
