### ISSUE TITLE
Popular Teaching Playlist Only Pulling 3 videos

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#506]
Help? https://www.themeetinghouse.com/teaching

**Comment by JonEsparaz** [comment]
I took a quick look at this. It's technically, "working as expected", but given changes in view statistics during the pandemic started some adjustments might be need.

Explanation:
- We only record the view count if the video has more than 1000 views. We do this to to keep our YouTube API quota under control (also videos with less than 1000 views are hypothetically not that popular).
https://github.com/themeetinghouse/web/blob/76e183db3a59018dcd3be66ebe0d5f73c50fe45d/src/components/ImportYoutube/ImportYoutube.ts#L331
- We only display a video in the popular teaching playlist if it has more than 1200 views and is from the last 120 days
https://github.com/themeetinghouse/web/blob/76e183db3a59018dcd3be66ebe0d5f73c50fe45d/public/static/content/teaching.json#L72-L73

Since the pandemic started it appears that view counts has dropped significantly (Rebuilding the Church from Sept 21 and 28 have ~700 views), so there aren't many videos from the last 120 days that meet the current view requirements, hence why there are only three videos in the playlist.

Recommended solution:
- Lower threshold for recording view count to 500 (hopefully this doesn't kill the API quota)
- Lower threshold for displaying videos to 700

**Comment by georgevicbell** [comment]
Other option is to include live videos in the popular videos, since they are regularly getting 3000+ views...


George Bell
Cell: 416-802-6697

________________________________

**Comment by deeinstereo** [comment]
@GeorgeBellTMH then the page will be overrun with too many videos from the livestream. I actually prefer @JonEsparaz 's suggestion. Can we tweak the numbers a little bit though, so that it does focus on the most popular ones?
Let's do:

- Lower threshold for recording view count to 700

- Lower threshold for displaying videos to 900
