### ISSUE TITLE
Livestream live id

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#568]
Is it currently possible to enter a zoom link rather than a youtube link in the Live Id field? We have an event in January (Ears to Hear) which will likely be a zoom call, but we want to make it available for people to join in.

**Comment by georgevicbell** [comment]
No. We will have to design an admin feature “service provider” that allows for YouTube or zoom...I’m not sure if zoom has an embeddable player....so it will have to show a link instead of video player.

Sent from my iPhone

On Nov 17, 2020, at 4:41 PM, Lucas Belem <notifications@github.com> wrote:

﻿

Is it currently possible to enter a zoom link rather than a youtube link in the Live Id field? We have an event in January (Ears to Hear) which will likely be a zoom call, but we want to make it available for people to join in.

**Comment by JonEsparaz** [comment]
Zoom has a web SDK: https://github.com/zoom/sample-app-web

But as George suggests, a link might be the better solution.

**Comment by deeinstereo** [comment]
Yeah @lucastbelem thinking more about it I don't think we'd use the LIVE button for this. I'd come up with another solution. @JonEsparaz and @GeorgeBellTMH this might be a good time for us to start thinking about how to handle people joining live events, like a Ears to Hear on a Zoom Call, or AGM, Town Halls etc. Events that are not necessarily livestream broadcasts per say.

**Comment by GeorgeBellTMH** [comment]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/47749730/99469134-0f6dc600-2910-11eb-96bf-c74eb4576155.png">

That's my idea....

**Comment by GeorgeBellTMH** [comment]
Clicking on join takes you directly to it...clicking on the title or time takes you to a page with a description...

**Comment by GeorgeBellTMH** [comment]
Join is maybe greyed out until it's the correct time....potentially we could add a "list all upcoming live events" button at the bottom that takes you to a page where you can filter and sort by time, date and location...

**Comment by deeinstereo** [comment]
@GeorgeBellTMH woah, that's pretty cool. Minor tweaks needed but yeah, can we have this in time for the January 10 Ears to Hear event and use it as a test for that event? I would also probably call the button "Live Events"

**Comment by GeorgeBellTMH** [comment]
The cool thing is that it would also work for Sundays....and Christmas....multiple events on the same day...

**Comment by deeinstereo** [comment]
ETA on how long it would take to develop consider our other priorities and the app?

**Comment by GeorgeBellTMH** [comment]
So we have the following to do:

1) Change the backend to allow for multiple event types (zoom, YouTube, LiveStream, others...), and an option to make event live on homepage (or just in the secondary page) - maybe 1-2 days
2) Change the frontend to pull and display (1-2 days)
3) Add a search/filter page with all events on frontend (1-2 days)
4) Permissions and ability for other people to add events?

My thought is we should have it before Christmas so we can have the 3 services listed...ideally we test it in mid-december...

**Comment by lucastbelem** [comment]
This stuff looks dope! Love it!

We're talking 3-6 days?

I think it's too optimistic for everything we need to deliver in JC by the end of the year - all of the payment, sign in, new modules, navigation, and new content injest for curriculum. I'd be hard pressed to prioritize this before the new year unless you @GeorgeBellTMH told me we're ahead of schedule and are going to be fine to add another 3-6 days of work on top of this scope. 

This means we couldn't do it for Jan 10th either as we hit Christmas break at that point. We have 2 contingency weeks from Jan 10-22 that could be a spot for this if things are on track.

Thoughts?

**Comment by itbel** [comment]
I'm almost done with the implementation for this that was discussed in the previous meeting. 
I was wondering what kind of message should display in the yellow bar. If we want to make it so banner messages are set per event we will need to implement a ticker on the homepage as well so that it would update between events.
Would this be okay? @GeorgeBellTMH 
Otherwise we can just have a hardcoded message. @deeinstereo 
![2](https://user-images.githubusercontent.com/42515854/101961989-f8ea2000-3bd8-11eb-9b88-9eed987d273d.png)
![1](https://user-images.githubusercontent.com/42515854/101961991-f982b680-3bd8-11eb-8d6e-449d9785450b.png)
