### ISSUE TITLE
Issue with videos not coming to /admin

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#632]
Hey team,

We're still having this problem and it's becoming a significant one. Could we please take a look to see what the issue might be?

In particular, there is a video (youtube id: cPiioNQzBzg) that is needed for this Sunday and it's on all the appropriate playlists, but doesn't show in admin. If someone could take a look at this one soon that would be great. Especially for the kids videos, it's impacting our Sunday morning as the video isn't showing up in time and then we have coordinators and parents contacting us.

Additionally, there are a number of errors that the console is returning for videos that never showed up on admin. I checked the ids and I think they are legacy teaching videos that got uploaded a few months ago.  Thanks team!

Here is a screenshot of the error:
<img width="1438" alt="Screen Shot 2021-01-09 at 11 26 50 AM" src="https://user-images.githubusercontent.com/48295718/104103023-eb729500-526d-11eb-8ac5-45cde6f508bf.png">

**Comment by lucastbelem** [comment]
@JonEsparaz @GeorgeBellTMH @itbel the video with the youtube id I included in the description above is needed for this Sunday and we do have coordinators looking for them already as we normally have the video up by end of day Thursday.

**Comment by JonEsparaz** [comment]
I'm looking into this. I have a suspicion what the issue is.

**Comment by JonEsparaz** [comment]
@lucastbelem uhhhh. The video is there already, but under Preschool, not Unlisted. Perhaps someone moved all these "missing" videos, then forgot about them? 

Have you guys only been looking in Unlisted?

![image](https://user-images.githubusercontent.com/48423418/104105824-f681f100-527e-11eb-9d49-94fedd815cbf.png)

**Comment by JonEsparaz** [comment]
Something odd is the published date is in the future (2020-01-10, tomorrow).

**Comment by JonEsparaz** [comment]
> Something odd is the published date is in the future (2020-01-10, tomorrow).

Wait it's 2021... So the published date is far in the past, which placed it at the back of the list:

![image](https://user-images.githubusercontent.com/48423418/104106039-a2780c00-5280-11eb-9f93-8f367451e745.png)

But it does appear on https://www.themeetinghouse.com/teaching-kids-youth

**Comment by JonEsparaz** [comment]
> Additionally, there are a number of errors that the console is returning for videos that never showed up on admin. I checked the ids and I think they are legacy teaching videos that got uploaded a few months ago. Thanks team!

These errors are not relevant. I'll edit the code to silence the errors unless an operation has actually failed.

**Comment by lucastbelem** [comment]
> @lucastbelem uhhhh. The video is there already, but under Preschool, not Unlisted. Perhaps someone moved all these "missing" videos, then forgot about them? 
> 
> Have you guys only been looking in Unlisted?
> 
> ![image](https://user-images.githubusercontent.com/48423418/104105824-f681f100-527e-11eb-9d49-94fedd815cbf.png)

@JonEsparaz Sorry to have wasted your time with this, Jon. I got a text this morning saying it wasn't up and assumed the person had done all the usual checks, so I only saw that it didn't appear under unlisted. I changed the date and the video is good now.

But we do have a large amount of videos that were uploaded to YouTube via a script that I haven't been able to find in admin. In light of the user error today, I'll take another closer look to make sure that's still true, but we may have a lot of ids to investigate.

**Comment by GeorgeBellTMH** [comment]
It might be helpful to make a view of all the videos and what folder they are in with a filter by id field.

**Comment by JonEsparaz** [comment]
> @JonEsparaz Sorry to have wasted your time with this, Jon. I got a text this morning saying it wasn't up and assumed the person had done all the usual checks, so I only saw that it didn't appear under unlisted. I changed the date and the video is good now.
> 
> But we do have a large amount of videos that were uploaded to YouTube via a script that I haven't been able to find in admin. In light of the user error today, I'll take another closer look to make sure that's still true, but we may have a lot of ids to investigate.

@lucastbelem not a problem - glad we got this sorted.

I'd like to get the issue at large solved because I've looked into the missing videos problem probably a dozen times now. I have my doubts that there's an actual bug as it always seems to be a data entry issue.

There's a lot of moving parts, so clearly documenting occurrences of this issue would be helpful if we are to determine if a bug exists. Whenever there's a missing video, adding the following information to a Google Sheet would be helpful:
- video ID
- playlist ID
- when was the issue observed (date/time)
- how/when the video was uploaded
- how/when the playlist was created
- how/when was the video added to the playlist
- was the video ever marked as private or unlisted?
- result: data entry issue, video magically appears on admin, video never appeared on admin

Question: are there actually videos (without data entry issues) that have never appeared on admin? It seems that the videos always magically appear after a few days.

Final note (this is a theory): if there is a "bug", it is probably just the behaviour of YouTube API. We could have some resolution if the behaviour is deterministic (e.g. videos uploaded via method A take longer to appear than videos uploaded method B). Or we might be at the mercy of YouTube's infrastructure (e.g. too many meme videos were posted in Canada the same hour we uploaded a video, so it takes longer to become accessible via the YouTube API).

**Comment by lucastbelem** [comment]
This hasn't been a problem in a long while, so I'm gonna consider it solved for now.

**Comment by lucastbelem** [comment]
@laurengermain

**Comment by laurengermain** [comment]
Here's the spreadsheet we can use to keep track of these issues, based on Jon's suggestions...

[https://docs.google.com/spreadsheets/d/1WMDLTv0-fCk3Y_S_Bjrk95ozPidfnd-liJrCS1T5vKY/edit#gid=0]

**Comment by lucastbelem** [comment]
Closing this for now as it should be fixed and we've opened another at #920
