### ISSUE TITLE
📗 Linkable Blog Titles 📗

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#646]
Can we make the titles of the blog posts from the preview posts (like on homepage or the covid page) clickable links to the blog? I know we have the Read More button, but I was looking at our dead clicks reports from CrazyEgg and there is a consistent pattern of users clicking on the title instead of Read More.

**Comment by JonEsparaz** [comment]
There might be some confusion for users because other blog components (e.g. on [themeetinghouse.com/blog](https://themeetinghouse.com/blog)) are completely wrapped in a `<Link/>` component, so everything (image, title, text) is clickable.

For the consistency, I would recommend doing the same for the multiImage blog component (wrap in a link to make everything clickable). Consider removing 'Read more' since it becomes a little redundant.

**Comment by deeinstereo** [comment]
@JonEsparaz <-- What he said. Let's get this done!
