### ISSUE TITLE
NPM Install Issue

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#672]
When running npm install we get:

Running it with npm install --legacy-peer-deps works...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tmh-web3@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.7.0" from @aws-amplify/ui-react@0.2.37
npm ERR! node_modules/@aws-amplify/ui-react
npm ERR!   @aws-amplify/ui-react@"^0.2.34" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/georgebell/.npm/eresolve-report.txt for a full report.

**Comment by JonEsparaz** [comment]
You're trying to install `@aws-amplify/ui-react@0.2.37`, right?

The error message tells us that there is a peer dependency of `react@^16.7.0`. Since this project relies on AWS Amplify's component library, the semantically correct thing to do is downgrade to React 16: `npm i @aws-amplify/ui-react@0.2.37 react@16 react-dom@16`

This open PR will support React 17: https://github.com/aws-amplify/amplify-js/pull/7651

**Comment by GeorgeBellTMH** [comment]
Kinda what I figured…gonna leave it as it is for now…it wasn’t causing problems before v7, and it looks like there are no code changes in that PR. I’ll take a look again early next week and see if they have fixed it.

G

**Comment by JonEsparaz** [comment]
FYI `@aws-amplify/ui-react@1.0.1` was released and now supports React 17.

**Comment by GeorgeBellTMH** [comment]
updated it...there is still a problem with google maps giving a similar error...but with no updates in 10 months its unlikely to get fixed anytime soon....gonna close this as the workaround is fine...
