### ISSUE TITLE
Youth times/locations on parish pages

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#716]
I'm wondering if it might be helpful to add time/date/email info for each parish's youth program on the parish page? 

Right now the only way to get this information is from the tmh youth external site, which is somewhat hard to get to from parish pages...and requires you to search again...

My suggestion is to add the information in a youth.json file and add it as a grey box below the kids and youth section on each parish page...if info is not set, it doesn't appear.

Time: 
Location: 
Contact Youth Pastor/Coordinator

For now locations would be all set to Online.

**Comment by GeorgeBellTMH** [comment]
Cc @lucastbelem and @deeinstereo

**Comment by deeinstereo** [comment]
@GeorgeBellTMH I like this! We have to revisit the youth experience on the website either way, but until we do that, this would be the best small step we could take. 
BUT>> I know they are quite protective over youth info due to plan to protect, so maybe date + time, and then youth pastor info is all we need on there. Second thought >> should we add Youth Pastors to relevant staff teams? For example, Sarah is the Youth pastor for Toronto, so she should appear in the team section for each of the Toronto Parishes, no?
Also, if we do anything I want to make sure we talk to Chris and Emma to get them involved. I think this would make them very happy @lucastbelem

**Comment by GeorgeBellTMH** [comment]
Yup on their page they have the youth pastors phone/email, so that would be fine. Also there is insta/fb for some parishes...not sure if we want to link/show that as well...

At some point we should switch the default URL for tmhyouth/underground....

**Comment by GeorgeBellTMH** [comment]
https://www.themeetinghouse.com/oakvilleyouthtest 

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/47749730/112720627-e4a30800-8ed5-11eb-807b-46407b5f474b.png">

**Comment by GeorgeBellTMH** [comment]
To add this to a parish page:

 {
        "type": "content",
        "style": "youth",
        "class": "locations",
        "filterField": "id",
        "filterValue": "oakville"
      },

and change the filterValue as appropriate...

Add the data in static/data/locations.json:

"youth": {
      "age": "Youth | Grades 6 – 12",
      "location": {
        "name": "The Meeting House Production Site",
        "googleMapLink": "https://www.google.com/maps/place/2700+Bristol+Cir,+Oakville,+ON+L6H+6E1/@43.5111777,-79.687309,17z/data=!3m1!4b1!4m5!3m4!1s0x882b43061295ed3d:0x6c6d4c16d7ec8f0e!8m2!3d43.5111738!4d-79.685115"
      },
      "time": "Wednesdays | 7:00 – 9:00 pm",
      "facebook": "https://www.facebook.com/oakvilleyouth.tmh/",
      "instagram": "https://www.instagram.com/oakvilleyouth.tmh/",
      "mainContact": {
        "name": "Brad Eager – Youth Pastor",
        "email": "brad.eager@themeetinghouse.com",
        "phone": "905.464.0307"
      }
    }

**Comment by GeorgeBellTMH** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/47749730/112720837-26807e00-8ed7-11eb-90b1-132ea551d91d.png">

Added covid info

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH I think it would be better to put the youth data in a separate file (e.g. youth.json) because you will be (unnecessarily) more than doubling the amount of data requested whenever `Dataloader.getLocations()` is used.

**Comment by JonEsparaz** [comment]
Also, on the location pages, you are requesting all the data twice (once in the hero component, once in the youth content component), which is a little inefficient.

**Comment by JonEsparaz** [comment]
> <img alt="image" width="520" src="https://user-images.githubusercontent.com/47749730/112720837-26807e00-8ed7-11eb-90b1-132ea551d91d.png">
> 
> Added covid info

@deeinstereo we use "COVID-19" around the website, right?

**Comment by deeinstereo** [comment]
@JonEsparaz Yup! COVID all caps, or COVID-19. But I think it's a little too much atm, most people assume that we're online due to covid so we don't need to specify. @GeorgeBellTMH yeah I'm not loving this design to be honest, also curious what this will look like on mobile, and I want to make sure we include the Youth team on this @lucastbelem can you take this on when the time is right?

**Comment by GeorgeBellTMH** [comment]
K, I'm leaving this till we get design/feedback

@JonEsparaz once we get all the data I'll move things to a separate file and fix up your comments and implement more stringent checks...

**Comment by GeorgeBellTMH** [comment]
Moved youth data to a separate file and created a map component...(still need someone in the know to populate the youth.json...

**Comment by GeorgeBellTMH** [comment]
Closing and tracking in #889
