### ISSUE TITLE
Livestreams won't update in admin

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#785]
A couple of pastors requested zoom link changes this morning. I went to /admin and "livestream" to make the update as usual. However, when I tried to save the livestream settings, nothing happened. My console just threw up a 401 error.

**Comment by JonEsparaz** [comment]
I don't think this is a bug per se. Did you try logging out and logging back in.

Recall:

https://github.com/themeetinghouse/web/pull/703#issuecomment-812516595

> @JonEsparaz was trying to move videos to Hidden this morning and got this error: Request failed with status code 401

https://github.com/themeetinghouse/web/pull/703#issuecomment-812536241

> All good. George said that means I should log out and log back in and that worked.

https://github.com/themeetinghouse/web/pull/703#issuecomment-812546524

> Yeah, for some example explanation, a 401 error code means unauthorized: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401.
> 
> Usually if you Google the error code you can figure out what's wrong.

**Comment by JonEsparaz** [comment]
If we want a "solution", I suggest adding try-catch log to admin that throws a toast or modal when there's a 401 error informing the user they need to reauthenticate.

**Comment by lucastbelem** [comment]
Ok makes sense. I didn't try logging out and back in...for some reason I
never think of that. My bad.

Yes to the toast idea (I love bread). But also, what can we do so that this
doesn't keep happening? I feel like every month or so something like this
comes up.

**Comment by JonEsparaz** [comment]
> But also, what can we do so that this doesn't keep happening? I feel like every month or so something like this comes up.

From what I can tell, the Cognito tokens expire after 7 days, but can persist in the browser's local storage even after expiration. 

Problem: if 7+ days pass and you've been visiting the admin pages (but don't actually make an authenticated API request) during that time, the tokens will persist in local storage (so you won't see the sign-in screen), but won't actually refresh (because tokens are refreshed on request only). 

Solution: force the tokens to refresh whenever the user opens an admin page by making a dummy API request. Simply calling `Auth.currentAuthenticatedUser()` should work: https://stackoverflow.com/a/53393460.

If this is done, the toast/modal likely isn't needed.

**Comment by GeorgeBellTMH** [comment]
This should get fixed in the upcoming versions of the site as we redo/add authentication for donations on the main site. 

I suspect we will add a pageConfig item that will add the auth pieces to specific pages in the background (eventually maybe even homepage) and a bunch of renderRouter components...so hopefully users get refreshed tokens more often. 

We can also definitely look at changing the timeouts, and handling the errors better.

**Comment by GeorgeBellTMH** [comment]
Closing...
