### ISSUE TITLE
Jamie Van Manen Picture cache issue

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#898]
@GeorgeBellTMH we made a mistake and named the picture with someone else's name. Now I've uploaded the correct picture, but the website thinks it's already online...it's one of those where I can't change the file name because it's the name of an overseers. Can you pls look into this and update the picture for Jamie?

Thanks.

**Comment by GeorgeBellTMH** [comment]
Can you take a look...I cleared it, but the image still looks wonky...

**Comment by GeorgeBellTMH** [comment]
Please note, I have added a new feature...in staff.json, coordinators.json and overseers.json you can add "ImageVersion":"2" to the json object...and it will append that to the filename:

So instead of George_Bell_app.jpg  it will look for George_Bell_app_2.jpg 

This should resolve caching issues...
